### Hello endpoint
GET http://localhost:8080/api/hello HTTP/1.1

### List products
# @name ProductList
GET http://localhost:8080/api/products HTTP/1.1

### Save product
# @name SaveProduct
POST http://localhost:8080/api/products HTTP/1.1
Content-Type: application/json

{
    "name": "Kiwi",
    "price": "90.00"
}

### Get Product
# @name GetProductById
GET http://localhost:8080/api/products/3 HTTP/1.1