server:
  port: 6001
spring:
  datasource:
    url: jdbc:mysql://localhost:3307/orderdb
    username: root
    password: generic
  application:
    name: order-service
  config:
    import: optional:configserver:http://localhost:8888
  jpa:
   show-sql: true
   hibernate:
    ddl-auto: update
    dialect: org.hibernate.dialect.MySQLDialect 
